---
title: "Recipie Engineering"
output: flexdashboard::flex_dashboard
runtime: shiny
resource_files:
- data/lm_fit.rda
- data/f.rda
- data/cook_time_fit.rda
- data/flavor_profile.rda
- data/lr_recipe.rda
- data/indian_food.rda
- data/ingr_list.rda
- data/ingredients.rda
---

```{r setup, include=FALSE}
#remotes::install_github("bayanalfaifi/Alfaifi")
knitr::opts_chunk$set(echo = TRUE)
#pacman::p_load(shiny, tidymodels, tidyverse, Alfaifi)
library(shiny)
library(tidymodels)
library(tidyverse)
library(glmnet)
#pacman::p_load(shiny, tidymodels, tidyverse)
```


```{r, include=FALSE}
load("data/cook_time_fit.rda")
load("data/prp_time_fit.rda")
load('data/f.rda')
load('data/flavor_profile.rda')
load('data/indian_food.rda')
load('data/ingr_list.rda')
load('data/ingredients.rda')
#load('data/lm_fit.rda')
#load('data/lr_mod.rda')
#load('data/lr_recipe.rda')
```

Column {.sidebar}
---------------------------------------------------------------
```{r input1, echo=FALSE}
selectInput(
  "ingr",
  "Please select ingredients",
  ingr_list,
  selected = "sugar",
  multiple = TRUE,
  selectize = TRUE,
  width = NULL,
  size = NULL
)

```


```{r input2, echo=FALSE}
selectInput(
  "flav",
  "Please select flavor",
  flavor_profile,
  selected = "sweet",
  multiple = FALSE,
  selectize = TRUE,
  width = NULL,
  size = NULL
)

```


Column {.tabset}
-------------------------------------
```{r ,echo=FALSE}
user_selection <- 
  reactive({
    ingredients %>%
      mutate(id=1L) %>% 
      select(id, ingredient) %>% 
      distinct() %>% 
      mutate(value = as.integer(ingredient %in% input$ingr)) %>%
      mutate( flavor_profile = input$flav) %>% 
      pivot_wider(names_from = "ingredient", values_from = "value") 
  })
```  



```{r, echo=FALSE}
results_cook_time <-  
  reactive ({
    predict(cook_time_fit, new_data = user_selection())
}) 
#in here we put  the reaction function to the code to let it activate when the users enter their ingrediants 

```
   
   
### Cook Time  

```{r, echo=FALSE}
renderText({
  as.character(results_cook_time())
})
  #in here we put the render to display the result for cook time 
```



```{r, echo=FALSE}
results_prep_time <-  
  reactive ({
    predict(prp_time_fit, new_data = user_selection())
}) 
#in here we put  the reaction function to the code to let it activate when the users enter their ingrediants 

```
   
   
### prep Time  

```{r, echo=FALSE}
renderText({
  as.character(results_prep_time())
})
  #in here we put the render to display the result for cook time 
```
